@startuml
!include .\\intermediaire\transition.puml
!include .\\Jeu_court\Jauge.puml
!include .\\Jeu_court\JeuCourt.puml
!include .\\Menu\Chargement.puml
!include .\\Menu\coce_i_menu.puml
!include .\\scenes\Intermediaire.puml
!include .\\Jeu_court\affichage\affichage.puml
!include .\\Jeu_court\DB\GestionDb.puml
!include .\\Jeu_court\Objectif\Formation.puml
!include .\\Jeu_court\Objectif\Projet.puml
!include .\\Jeu_court\Planning\Agenda.puml
!include .\\Jeu_court\Planning\jour.puml
!include .\\Jeu_court\Planning\Rendezvous.puml
!include .\\Jeu_court\Question\question.puml
!include .\\.godot\mono\temp\obj\Debug\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\.godot\mono\temp\obj\Debug\university-simulator.AssemblyInfo.puml
!include .\\.godot\mono\temp\obj\ExportDebug\win-x64\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\.godot\mono\temp\obj\ExportDebug\win-x64\university-simulator.AssemblyInfo.puml
@enduml
