@startuml umlV1.puml
package questions {
    abstract class Question {
        #m_reponse1: Reponse
        #m_reponse2: Reponse

        +<<Create>>Question():
        +{abstract} afficher(): void
    }
    
    class QuestionRDV extends Question {

        +<<Create>>QuestionRDV():
        +afficher(): void
    }

    class QuestionFormation extends Question {

        +<<Create>>QuestionCreateFormation():
        +afficher(): void
    }

    class QuestionProf extends Question {

        +<<Create>>QuestionProf():
        +afficher(): void
    }

    class QuestionEtudiant extends Question {

        +<<Create>>QuestionEtudiant():
        +afficher(): void
    }

    class QuestionFond extends Question {

        +<<Create>>QuestionFond():
        +afficher(): void
    }

    class QuestionCompetence extends Question {

        +<<Create>>QuestionCompetence():
        +afficher(): void
    }

    class QuestionMarcheTravail extends Question {

        +<<Create>>QuestionMarcheTravail():
        +afficher(): void
    }
}
package reponses
{
    class Reponse {
        +m_texte: String
        +m_jaugeArgent: Integer
        +m_jaugeSatisfProf: Integer
        +m_jaugeInserPro: Integer
        +m_jaugeReussiteEtu: Integer

        +<<Create>>Reponse():
        +afficher(): void
    }
}
package jauges {
    class JaugeArgent <<static>> {
        -m_actuel: Integer
        -m_max: Integer
        -m_min: Integer

        +remplirVider(quantite: Integer): void
    }

    class JaugeSatisfProf <<static>> {
        -m_actuel: Integer
        -m_max: Integer
        -m_min: Integer

        +remplirVider(quantite: Integer): void
    }

    class JaugeInserPro <<static>> {
        -m_actuel: Integer
        -m_max: Integer
        -m_min: Integer

        +remplirVider(quantite: Integer): void
    }

    class JaugeReussiteEtu <<static>> {
        -m_actuel: Integer
        -m_max: Integer
        -m_min: Integer

        +remplirVider(quantite: Integer): void
    }

}

Question "1" *-->"m_reponse1\n1"Reponse : possede
Question "1" *-->"m_reponse2\n1"Reponse : possede
Reponse .> JaugeArgent : <<uses>>
Reponse .> JaugeSatisfProf : <<uses>>
Reponse .> JaugeInserPro : <<uses>>
Reponse .> JaugeReussiteEtu : <<uses>>
@enduml