@startuml
class Question {
    + Question()
    + getquestion(composante:int) : string
    + getnbquestion() : int
    + question_suivante(composante:int) : void
    + getnumquestion() : int
    + getvaleur1(j:string) : int
    + getvaleur2(j:string) : int
    + reponse1() : string
    + reponse2() : string
}
@enduml
