@startuml
class coce_i_menu <<partial>> {
    + <<override>> _Ready() : void
    + _on_b_court_pressed() : void
    + _on_b_long_pressed() : void
    + _on_b_quittez_pressed() : void
    + _on_b_son_pressed() : void
}
Control <|-- coce_i_menu
@enduml
